analysis/urls.py
from django.urls import path
from .views import (chart_select_view, 
                    add_purchase_view,
                    salesman_performance,
                    home_view,
                    )

app_name='analysis'

urlpatterns = [
    path('', home_view, name='home-view'),
    path('analysis/', chart_select_view, name='main-view'),
    path('add-purchase/', add_purchase_view, name='add-view'),
    path('salesman/', salesman_performance, name='sales_view'),
]

csvfile/urls.py
from django.urls import path
from .views import upload_file

app_name = 'csvfile'

urlpatterns = [
    path('', upload_file, name='upload-csv')
]

customers/urls.py
from django.urls import path
from .views import corr_customer

app_name = 'customers'

urlpatterns = [
    path('', corr_customer, name='customer_insight')
]

productsanalysis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import user_login_view, user_logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', user_login_view, name='login'),
    path('logout/', user_logout_view, name='logout'),
    path('', include('analysis.urls', namespace='analysis')),
    path('upload/',include('csvfile.urls', namespace='csvfile')),
    path('customer-insight/', include('customers.urls', namespace='customers'))
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!--REQUIREMENT META TAGS-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!--BULMA CSS-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"/>
    <link href="~bulma-calendar/dist/css/bulma-calendar.min.css" rel="stylesheet">
    <!-- Bootstrap css-->
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    -->

    <!--favicon-->
    <link rel="icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <!--CUSTOM CSS-->
    <link rel="stylesheet" href="{% static 'style.css' %}"/>
    <!--fontawesome-->
    <script src="https://kit.fontawesome.com/4ffa414c4a.js" crossorigin="anonymous"></script>
    
    <!--BULMA js-->
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <script src="~bulma-calendar/dist/js/bulma-calendar.min.js"></script>
    
    <!--dropzone-->
    <!--<script src="https://unpkg.com/dropzone@5/dist/min/dropzone.min.js"></script>-->
    <!--<link rel="stylesheet" href="https://unpkg.com/dropzone@5/dist/min/dropzone.min.css" type="text/css" />-->

    <!--Custom js-->
    <script src="{% static 'funct.js' %}" defer></script>
    
    {%  block scripts %}
    {% endblock scripts %}
    <title>analysis | {% block title %}{% endblock title %} </title>
</head>

<body>
    {% include 'navbar.html' %}
    <section class = "section">
        
                {% block content %}
                {% endblock content %}
        
    </section>
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="columns">
      {% if error_message %}
        <div class="column is-half is-offset-one-quarter">
          <div class="notification is-danger is-light has-text-centered">
            <button class="delete"></button>
            <strong>{{error_message}}</strong>
          </div>
        </div>
      {% endif %}
</div>
    
<div class="columns is-mobile is-centered">
      <div class="column is-4">
          <div class="content mt-4"><h2>User registration</h2></div>
          <form action="" method="POST">
              {% csrf_token %}
              {% for field in form %}
              <div class="field"> 
                <label for="{{ field.id_for_label }}" class="label">{{ field.html_name }}</label>
                {{ field }}
              </div>
              {% endfor %}
              <div class="control mt-5 has-text-centered">
                <button type="submit" class="button has-background-info-dark" style="width:250px;height:45px;"><span class="icon is-small">
                  <i class="fas fa-check"></i>
                </span>
                <span> login </span></button>
              </div>
          </form>
      </div>
</div>
{% endblock content %}

templates/navbar.html
{% url 'analysis:home-view' as path_to_home %}
{% url 'analysis:main-view' as path_to_dashboard %}
{% url 'analysis:add-view' as path_to_add_purchase %}
{% url 'csvfile:upload-csv' as path_to_upload_csv %}
{% url 'customers:customer_insight' as path_to_customer %}
{% url 'analysis:sales_view' as path_to_performance %}
{% url 'login' as path_to_login %}
{% url 'logout' as path_to_logout %}

{% load static %}

<nav class="navbar is-spaced is-dark mb-4" role="navigation" aria-label="main navigation">
      <div class="navbar-brand ml-6">
        <a class="navbar-item-img-max-height img-responsive" href={{path_to_home}}>
          <img src="{% static 'faviconweb.png' %}"  width="80" height="80">
        </a>
    
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navbarBasicExample" class="navbar-menu ml-2">
        <div class="navbar-start">
          
          <a class="navbar-item" href={{path_to_home}}>
            <strong>Home</strong>
          </a>

          <a class="navbar-item" href={{path_to_dashboard}}>
            <strong>Dashboard</strong>
          </a>

          <a class="navbar-item" href={{path_to_add_purchase}}>
            <strong>Purchase</strong>
          </a>

          <a class="navbar-item" href={{path_to_upload_csv}}>
            <strong>Upload</strong>
          </a>

          <a class="navbar-item" href={{path_to_customer}}>
            <strong>Customer</strong>
          </a>

          <a class="navbar-item" href={{path_to_performance}}>
            <strong>Performance</strong>
          </a>
        </div>
      
      
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons mr-6">
              <a class="button is-link" href={{path_to_login}}>
                <strong>Log in</strong>
              </a>
              <a class="button is-light" href={{path_to_logout}}>
                <strong>Sign up</strong>
              </a>
            </div>
          </div>
        </div>
      </div>
</nav>